In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_excel('./data/Stammdaten_Verkehrsdetektion_2022_07_20.xlsx')

In [6]:
y2, x2 = 52.51361000, 13.41883000 # Berlin Mitte
coordinates = df[['x', 'y', 'DET_ID15']]
unique_coordinates = coordinates.drop_duplicates(subset=['x', 'y'])
lower_bound = (52.400149, 13.066275)
upper_bound = (52.644374, 13.793748)
np.random.seed(9)
a = np.array(unique_coordinates)
np.random.shuffle(a)

used_traffic_station_list = []




for i, coor in enumerate(a):
    if i > 82:
        break
    used_traffic_station_list.append(int(coor[2]))
    print(coor[1], ',', coor[0], ',', int(coor[2]), ',', '#0000FF')
unique_coordinates

52.505503 , 13.36333619 , 100101010023712 , #0000FF
52.53473797 , 13.27843124 , 100101010016739 , #0000FF
52.51144335 , 13.3733365 , 100101010053822 , #0000FF
52.52062324 , 13.27995105 , 100101010035230 , #0000FF
52.53131551 , 13.29557448 , 100101010043516 , #0000FF
52.56605457 , 13.5122723 , 100101010055640 , #0000FF
52.48056663 , 13.34652074 , 100101010095046 , #0000FF
52.45854208 , 13.47857886 , 100101010054832 , #0000FF
52.44813757 , 13.43571359 , 100101010019163 , #0000FF
52.45207024 , 13.41966228 , 100101010003504 , #0000FF
52.50401729 , 13.3666166 , 100101010058367 , #0000FF
52.56719919 , 13.32917518 , 100101010013709 , #0000FF
52.48328162 , 13.2918667 , 100101010017547 , #0000FF
52.53957747 , 13.36507758 , 100101010061603 , #0000FF
52.46383059 , 13.31804085 , 100101010069077 , #0000FF
52.56687425 , 13.32908423 , 100101010013507 , #0000FF
52.48843966 , 13.33104097 , 100101010041900 , #0000FF
52.52418392 , 13.35407473 , 100101010081104 , #0000FF
52.50813441 , 13.35184161 , 100101010023914 , #0000FF
52.51174135 , 13.28147568 , 100101010069380 , #0000FF
52.52148393 , 13.26067151 , 100101010044324 , #0000FF
52.5638381 , 13.49795128 , 100101010041088 , #0000FF
52.49979843 , 13.32068505 , 100101010022092 , #0000FF
52.43728069 , 13.38816757 , 100101010078979 , #0000FF
52.51056827 , 13.32383634 , 100101010014113 , #0000FF
52.49977749 , 13.4789053 , 100101010011685 , #0000FF
52.52206752 , 13.35643582 , 100101010076555 , #0000FF
52.57754524 , 13.34778595 , 100101010004110 , #0000FF
52.44210104 , 13.37866395 , 100101010017951 , #0000FF
52.47682214 , 13.38587442 , 100101010079484 , #0000FF
52.50711384 , 13.3554024 , 100101010053620 , #0000FF
52.50663813 , 13.38890608 , 100101010066047 , #0000FF
52.49275611 , 13.36098709 , 100101010072717 , #0000FF
52.43750906 , 13.59532834 , 100101010019870 , #0000FF
52.56058538 , 13.49780177 , 100101010032200 , #0000FF
52.5085314 , 13.30218315 , 100101010099894 , #0000FF
52.57724622 , 13.39841485 , 100101010056448 , #0000FF
52.52133979 , 13.15663948 , 100101010053923 , #0000FF
52.49826234 , 13.38621035 , 100101010023207 , #0000FF
52.54734541 , 13.31654198 , 100101010062007 , #0000FF
52.51061763 , 13.39310269 , 100101010065138 , #0000FF
52.50055542 , 13.47758377 , 100101010011887 , #0000FF
52.51021537 , 13.38834798 , 100101010063017 , #0000FF
52.5262709 , 13.41651389 , 100101010086053 , #0000FF
52.46737011 , 13.44016281 , 100101010066855 , #0000FF
52.52856521 , 13.39407236 , 100101010030681 , #0000FF
52.51276325 , 13.40379339 , 100101010064633 , #0000FF
52.50974724 , 13.3788682 , 100101010093632 , #0000FF
52.45412319 , 13.57572448 , 100101010033311 , #0000FF
52.51972244 , 13.41325065 , 100101010062613 , #0000FF
52.507086 , 13.36905504 , 100101010015426 , #0000FF
52.55962242 , 13.55581247 , 100101010039977 , #0000FF
52.45321939 , 13.56893846 , 100101010020274 , #0000FF
52.58629742 , 13.3229274 , 100101010028459 , #0000FF
52.45416683 , 13.57586572 , 100101010033513 , #0000FF
52.48856087 , 13.35867996 , 100101010022496 , #0000FF
52.5285437 , 13.38050804 , 100101010091309 , #0000FF
52.4948426 , 13.32806856 , 100101010052812 , #0000FF
52.52985745 , 13.42546565 , 100101010034119 , #0000FF
52.5161646 , 13.35312673 , 100101010025126 , #0000FF
52.52086178 , 13.40598689 , 100101010081407 , #0000FF
52.46746233 , 13.38577635 , 100101010097470 , #0000FF
52.5105879 , 13.31468272 , 100101010077161 , #0000FF
52.50971353 , 13.41543408 , 100101010060993 , #0000FF
52.49857823 , 13.33046363 , 100101010073525 , #0000FF
52.43541924 , 13.25433876 , 100101010035836 , #0000FF
52.50520567 , 13.39693916 , 100101010067360 , #0000FF
52.51427863 , 13.46984019 , 100101010068774 , #0000FF
52.4985548 , 13.46090916 , 100101010068269 , #0000FF
52.41615714 , 13.4000522 , 100101010002288 , #0000FF
52.50707338 , 13.36912844 , 100101010015325 , #0000FF
52.41487617 , 13.36441331 , 100101010002086 , #0000FF
52.56965869 , 13.47923485 , 100101010009766 , #0000FF
52.43511242 , 13.26310552 , 100101010001076 , #0000FF
52.50331881 , 13.37342706 , 100101010058569 , #0000FF
52.53825763 , 13.42662017 , 100101010026742 , #0000FF
52.55159764 , 13.35380019 , 100101010007948 , #0000FF
52.57307371 , 13.31246737 , 100101010028661 , #0000FF
52.5107973 , 13.31448025 , 100101010073727 , #0000FF
52.57670433 , 13.34798158 , 100101010003908 , #0000FF
52.556345 , 13.38465351 , 100101010059781 , #0000FF
52.49628942 , 13.3925616 , 100101010074838 , #0000FF
52.51075032 , 13.39348412 , 100101010064936 , #0000FF

             x          y         DET_ID15
0    13.192578  52.433868  100101010000167
2    13.192747  52.433813  100101010000369
4    13.261301  52.436642  100101010000874
6    13.263106  52.435112  100101010001076
8    13.259881  52.433741  100101010001278
..         ...        ...              ...
572  13.385776  52.467462  100101010097470
574  13.383970  52.457794  100101010097672
576  13.384196  52.457440  100101010097874
578  13.301719  52.509232  100101010099692
580  13.302183  52.508531  100101010099894

[284 rows x 3 columns]

In [7]:
print(used_traffic_station_list)

[100101010023712, 100101010016739, 100101010053822, 100101010035230, 100101010043516, 100101010055640, 100101010095046, 100101010054832, 100101010019163, 100101010003504, 100101010058367, 100101010013709, 100101010017547, 100101010061603, 100101010069077, 100101010013507, 100101010041900, 100101010081104, 100101010023914, 100101010069380, 100101010044324, 100101010041088, 100101010022092, 100101010078979, 100101010014113, 100101010011685, 100101010076555, 100101010004110, 100101010017951, 100101010079484, 100101010053620, 100101010066047, 100101010072717, 100101010019870, 100101010032200, 100101010099894, 100101010056448, 100101010053923, 100101010023207, 100101010062007, 100101010065138, 100101010011887, 100101010063017, 100101010086053, 100101010066855, 100101010030681, 100101010064633, 100101010093632, 100101010033311, 100101010062613, 100101010015426, 100101010039977, 100101010020274, 100101010028459, 100101010033513, 100101010022496, 100101010091309, 100101010052812, 100101010034119, 100101010025126, 100101010081407, 100101010097470, 100101010077161, 100101010060993, 100101010073525, 100101010035836, 100101010067360, 100101010068774, 100101010068269, 100101010002288, 100101010015325, 100101010002086, 100101010009766, 100101010001076, 100101010058569, 100101010026742, 100101010007948, 100101010028661, 100101010073727, 100101010003908, 100101010059781, 100101010074838, 100101010064936]